name: romid
channels:
  - conda-forge
dependencies:
  - python=3.11
  - fenics-dolfinx=0.9
  - mpich
  - gmsh
  - meshio
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - pytest
  - pip
  - pip:
      - -e .
